// channels_terminal.go registers the terminal.* wscompat channels
// (SSH/dev-server PTY control-plane) against infra-fleet-service's
// Terminal/PTY gRPC surface added by TASK-180..185, including piping
// AttachPty's server-pushed output/exit frames into the WS push bridge
// (registry.go's StreamChannelHandler + push_bridge.go's pipePush).
//
// terminal.create is registered via Registry.RegisterStreamChannel, not
// Registry.Register: its invoke must both ack with the new TerminalSession
// (the caller needs the ptyId back) AND open a live subscription that keeps
// delivering terminal.output/terminal.exited push frames for the rest of the
// pty's life — see registry.go's StreamChannelHandler doc comment for why
// this needs its own registration path alongside the existing plain
// ChannelHandler (Register/Dispatch) and pure-subscribe StreamHandler
// (RegisterStream/notifications.subscribe's precedent, which has no ack).
//
// # Per-connection stream registry
//
// terminalStreamRegistry maps pty_id -> its live AttachPty stream, but there
// is one INSTANCE PER WEBSOCKET CONNECTION, not one shared process-wide: it
// is constructed once in Handler.ServeHTTP (handler.go) and threaded through
// ctx via terminalStreamsContext/terminalStreamsFromContext below, the same
// way every other per-connection concern in this package rides ctx rather
// than a package-level variable. This matters because pty_id is generated by
// infra-fleet-service and is NOT guaranteed unique across unrelated WS
// connections belonging to different tenants/users — a single shared
// registry would let one connection's terminal.send reach another
// connection's stream if their pty_ids ever collided.
package wscompat

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"

	infrafleetv1 "github.com/stablyai/orca-go/proto/gen/go/orca/infrafleet/v1"

	gatewaygrpc "github.com/stablyai/orca-go/services/api-gateway/internal/adapter/grpc"
	"github.com/stablyai/orca-go/services/api-gateway/internal/usecase"
)

// terminalStreamEntry is one live AttachPty stream — sendMu serializes
// stream.Send calls, since a grpc.ClientStream forbids concurrent senders
// (mirrors Handler.ServeHTTP's own writeMu discipline for the same
// underlying reason, see handler.go).
type terminalStreamEntry struct {
	stream infrafleetv1.InfraFleetService_AttachPtyClient
	cancel context.CancelFunc

	sendMu sync.Mutex
}

func (e *terminalStreamEntry) send(frame *infrafleetv1.PtyClientFrame) error {
	e.sendMu.Lock()
	defer e.sendMu.Unlock()
	return e.stream.Send(frame)
}

// terminalStreamRegistry maps pty_id -> its live AttachPty stream, scoped to
// ONE WebSocket connection — see this file's package doc comment.
type terminalStreamRegistry struct {
	mu      sync.Mutex
	streams map[string]*terminalStreamEntry
}

func newTerminalStreamRegistry() *terminalStreamRegistry {
	return &terminalStreamRegistry{streams: make(map[string]*terminalStreamEntry)}
}

func (r *terminalStreamRegistry) put(ptyID string, entry *terminalStreamEntry) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.streams[ptyID] = entry
}

func (r *terminalStreamRegistry) get(ptyID string) (*terminalStreamEntry, bool) {
	r.mu.Lock()
	defer r.mu.Unlock()
	e, ok := r.streams[ptyID]
	return e, ok
}

// remove deletes and returns ptyID's entry, if any — terminal.close's
// cleanup path, and drainAttachPtyOutput's own cleanup once its stream ends.
func (r *terminalStreamRegistry) remove(ptyID string) (*terminalStreamEntry, bool) {
	r.mu.Lock()
	defer r.mu.Unlock()
	e, ok := r.streams[ptyID]
	delete(r.streams, ptyID)
	return e, ok
}

// terminalStreamsCtxKey is the context key terminalStreamsContext/
// terminalStreamsFromContext use to thread one connection's
// terminalStreamRegistry through every terminal.* handler call on that
// connection, without a package-level shared instance.
type terminalStreamsCtxKey struct{}

// terminalStreamsContext attaches streams as ctx's per-connection terminal
// stream registry. Called once per WebSocket connection, from
// Handler.ServeHTTP (handler.go), before that connection's read/dispatch
// loop starts.
func terminalStreamsContext(ctx context.Context, streams *terminalStreamRegistry) context.Context {
	return context.WithValue(ctx, terminalStreamsCtxKey{}, streams)
}

// terminalStreamsFromContext resolves the calling connection's
// terminalStreamRegistry, or nil if ctx was never wrapped by
// terminalStreamsContext (a wiring bug — every real request path wraps it in
// ServeHTTP; only a test that dispatches directly without doing so would see
// nil).
func terminalStreamsFromContext(ctx context.Context) *terminalStreamRegistry {
	streams, _ := ctx.Value(terminalStreamsCtxKey{}).(*terminalStreamRegistry)
	return streams
}

// errNoTerminalStreamRegistry is returned when a terminal.* handler can't
// find a per-connection terminalStreamRegistry on ctx — see
// terminalStreamsFromContext's doc comment.
var errNoTerminalStreamRegistry = fmt.Errorf("wscompat: no per-connection terminal stream registry on context (internal wiring bug)")

// registerTerminalChannels wires every terminal.* channel this pass gives
// real backend-go logic to. Called from RegisterRealChannels (channels.go).
func registerTerminalChannels(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	registerTerminalCreateChannel(r, client)
	registerTerminalSendChannel(r)
	registerTerminalResizeChannel(r, client)
	registerTerminalCloseChannel(r, client)
	registerTerminalStopChannel(r, client)
	registerTerminalListChannel(r, client)
	registerTerminalWaitChannel(r, client)
	registerTerminalFocusChannel(r, client)
	registerTerminalAgentStatusChannels(r, client)
	registerTerminalInspectProcessChannel(r, client)
}

// terminalSessionView is the wire shape terminal.create/terminal.list
// return — mirrors TerminalSession's proto fields with unix-millisecond
// timestamps (JSON-friendlier than a Timestamp message).
type terminalSessionView struct {
	PtyID        string `json:"ptyId"`
	ConnectionID string `json:"connectionId"`
	Cwd          string `json:"cwd"`
	CreatedAt    int64  `json:"createdAt"`
	LastActiveAt int64  `json:"lastActiveAt"`
}

func toTerminalSessionView(s *infrafleetv1.TerminalSession) terminalSessionView {
	return terminalSessionView{
		PtyID:        s.GetPtyId(),
		ConnectionID: s.GetConnectionId(),
		Cwd:          s.GetCwd(),
		CreatedAt:    s.GetCreatedAtUnixMs(),
		LastActiveAt: s.GetLastActiveAtUnixMs(),
	}
}

// attachContext builds the long-lived, identity-stamped context an AttachPty
// stream needs. Deliberately NOT derived from the invoke's own ctx: every
// wscompat invoke is bounded by handler.go's 25s invokeTimeout
// (handleInvoke wraps ctx in context.WithTimeout before calling
// Registry.Dispatch) — an AttachPty stream inherited from that ctx would be
// killed 25 seconds after terminal.create, mid-session, for every terminal
// pane. context.Background() plus the same identity metadata
// gatewaygrpc.AttachIdentity stamps on every other outbound call keeps the
// stream alive for the pty's real lifetime instead; terminal.close's cancel()
// is the only thing that ends it deliberately.
func attachContext(id Identity) (context.Context, context.CancelFunc) {
	ctx, cancel := context.WithCancel(context.Background())
	return gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID}), cancel
}

// ── terminal.create ─────────────────────────────────────────────────────

type terminalCreateArgs struct {
	ConnectionID string `json:"connectionId"`
	Cwd          string `json:"cwd"`
	Shell        string `json:"shell"`
	Cols         int32  `json:"cols"`
	Rows         int32  `json:"rows"`
}

func registerTerminalCreateChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.RegisterStreamChannel("terminal.create", func(ctx context.Context, id Identity, args []json.RawMessage) (any, <-chan PushEvent, error) {
		in, err := decodeArg[terminalCreateArgs](args, 0)
		if err != nil {
			return nil, nil, err
		}
		streams := terminalStreamsFromContext(ctx)
		if streams == nil {
			return nil, nil, errNoTerminalStreamRegistry
		}

		invokeCtx := gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		spawnResp, err := client.SpawnTerminalSession(invokeCtx, &infrafleetv1.SpawnTerminalSessionRequest{
			ConnectionId: in.ConnectionID,
			Cwd:          in.Cwd,
			Shell:        in.Shell,
			Cols:         in.Cols,
			Rows:         in.Rows,
		})
		if err != nil {
			return nil, nil, err
		}
		session := spawnResp.GetSession()

		// See attachContext's doc comment: the stream MUST outlive this
		// invoke's own 25s deadline.
		streamCtx, cancel := attachContext(id)
		stream, err := client.AttachPty(streamCtx)
		if err != nil {
			cancel()
			return nil, nil, fmt.Errorf("wscompat: opening AttachPty stream for pty %q: %w", session.GetPtyId(), err)
		}
		if err := stream.Send(&infrafleetv1.PtyClientFrame{
			Frame: &infrafleetv1.PtyClientFrame_Attach{Attach: &infrafleetv1.AttachToSession{PtyId: session.GetPtyId()}},
		}); err != nil {
			cancel()
			return nil, nil, fmt.Errorf("wscompat: sending AttachPty's initial attach frame for pty %q: %w", session.GetPtyId(), err)
		}

		entry := &terminalStreamEntry{stream: stream, cancel: cancel}
		streams.put(session.GetPtyId(), entry)

		events := make(chan PushEvent)
		go drainAttachPtyOutput(streamCtx, session.GetPtyId(), entry, streams, events)

		return toTerminalSessionView(session), events, nil
	})
}

// drainAttachPtyOutput reads every PtyServerFrame the agent pushes for one
// pty session until the stream ends (terminal.close's cancel(), the agent
// process exiting, or a transport error), forwarding each as a PushEvent on
// events — consumed by pipePush (handler.go's handleInvoke starts that
// goroutine right after acking terminal.create) so terminal output/exit
// reaches the browser in real time instead of being discarded.
//
// Removes ptyID from streams and closes events when the stream ends for ANY
// reason — closing events ends pipePush's read loop instead of leaving that
// goroutine parked forever on a stream nothing will ever write to again
// (terminal.close's own cancel() also unblocks a send that raced a slow/gone
// reader, via streamCtx.Done() below).
func drainAttachPtyOutput(streamCtx context.Context, ptyID string, entry *terminalStreamEntry, streams *terminalStreamRegistry, events chan<- PushEvent) {
	defer close(events)
	defer streams.remove(ptyID)
	for {
		frame, err := entry.stream.Recv()
		if err != nil {
			return // stream ended — io.EOF on a clean close, or a real transport error either way
		}
		switch f := frame.GetFrame().(type) {
		case *infrafleetv1.PtyServerFrame_Out:
			ev := PushEvent{Channel: "terminal.output", Args: []any{map[string]any{"ptyId": ptyID, "data": f.Out.GetData()}}}
			select {
			case events <- ev:
			case <-streamCtx.Done():
				return
			}
		case *infrafleetv1.PtyServerFrame_Exited:
			ev := PushEvent{Channel: "terminal.exited", Args: []any{map[string]any{"ptyId": ptyID, "exitCode": f.Exited.GetExitCode()}}}
			select {
			case events <- ev:
			case <-streamCtx.Done():
			}
			return
		}
	}
}

// ── terminal.send ───────────────────────────────────────────────────────

type terminalSendArgs struct {
	PtyID string `json:"ptyId"`
	Data  string `json:"data"`
}

func registerTerminalSendChannel(r *Registry) {
	r.Register("terminal.send", func(ctx context.Context, _ Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalSendArgs](args, 0)
		if err != nil {
			return nil, err
		}
		streams := terminalStreamsFromContext(ctx)
		if streams == nil {
			return nil, errNoTerminalStreamRegistry
		}
		entry, ok := streams.get(in.PtyID)
		if !ok {
			return nil, fmt.Errorf("wscompat: no live AttachPty stream for pty %q — call terminal.create first", in.PtyID)
		}
		if err := entry.send(&infrafleetv1.PtyClientFrame{
			Frame: &infrafleetv1.PtyClientFrame_Input{Input: &infrafleetv1.PtyInput{Data: []byte(in.Data)}},
		}); err != nil {
			return nil, err
		}
		return nil, nil
	})
}

// ── terminal.resize ─────────────────────────────────────────────────────
//
// Uses the unary ResizeTerminalSession RPC rather than AttachPty's in-stream
// PtyResize frame — simpler (no dependency on terminalStreamRegistry state)
// and the proto explicitly documents the in-stream frame as "the low-latency
// ALTERNATIVE to the unary RPC", i.e. the unary path is the primary one.

type terminalResizeArgs struct {
	PtyID string `json:"ptyId"`
	Cols  int32  `json:"cols"`
	Rows  int32  `json:"rows"`
}

func registerTerminalResizeChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.resize", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalResizeArgs](args, 0)
		if err != nil {
			return nil, err
		}
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		_, err = client.ResizeTerminalSession(ctx, &infrafleetv1.ResizeTerminalSessionRequest{PtyId: in.PtyID, Cols: in.Cols, Rows: in.Rows})
		return nil, err
	})
}

// ── terminal.close ──────────────────────────────────────────────────────

type terminalPtyIDArg struct {
	PtyID string `json:"ptyId"`
}

func registerTerminalCloseChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.close", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalPtyIDArg](args, 0)
		if err != nil {
			return nil, err
		}
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		_, killErr := client.KillTerminalSession(ctx, &infrafleetv1.KillTerminalSessionRequest{PtyId: in.PtyID})

		if streams := terminalStreamsFromContext(ctx); streams != nil {
			if entry, ok := streams.remove(in.PtyID); ok {
				entry.cancel() // ends drainAttachPtyOutput's Recv loop and the underlying stream
			}
		}
		return nil, killErr
	})
}

// ── terminal.stop ───────────────────────────────────────────────────────

func registerTerminalStopChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.stop", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalPtyIDArg](args, 0)
		if err != nil {
			return nil, err
		}
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		_, err = client.StopTerminalProcess(ctx, &infrafleetv1.StopTerminalProcessRequest{PtyId: in.PtyID})
		return nil, err
	})
}

// ── terminal.list ───────────────────────────────────────────────────────

type terminalListArgs struct {
	ConnectionID string `json:"connectionId"`
}

func registerTerminalListChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.list", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, _ := decodeArg[terminalListArgs](args, 0) // no args ("list everything") is valid, so ignore a decode error

		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		resp, err := client.ListTerminalSessions(ctx, &infrafleetv1.ListTerminalSessionsRequest{ConnectionId: in.ConnectionID})
		if err != nil {
			return nil, err
		}
		views := make([]terminalSessionView, 0, len(resp.GetSessions()))
		for _, s := range resp.GetSessions() {
			views = append(views, toTerminalSessionView(s))
		}
		return views, nil
	})
}

// ── terminal.wait ───────────────────────────────────────────────────────

type terminalWaitArgs struct {
	PtyID     string `json:"ptyId"`
	TimeoutMs int32  `json:"timeoutMs"`
}

type terminalWaitView struct {
	Exited   bool  `json:"exited"`
	ExitCode int32 `json:"exitCode"`
	TimedOut bool  `json:"timedOut"`
}

func registerTerminalWaitChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.wait", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalWaitArgs](args, 0)
		if err != nil {
			return nil, err
		}
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		resp, err := client.WaitTerminalSession(ctx, &infrafleetv1.WaitTerminalSessionRequest{PtyId: in.PtyID, TimeoutMs: in.TimeoutMs})
		if err != nil {
			return nil, err
		}
		return terminalWaitView{Exited: resp.GetExited(), ExitCode: resp.GetExitCode(), TimedOut: resp.GetTimedOut()}, nil
	})
}

// ── terminal.focus ──────────────────────────────────────────────────────

func registerTerminalFocusChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.focus", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalPtyIDArg](args, 0)
		if err != nil {
			return nil, err
		}
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		_, err = client.FocusTerminalSession(ctx, &infrafleetv1.FocusTerminalSessionRequest{PtyId: in.PtyID})
		return nil, err
	})
}

// ── terminal.agentStatus / terminal.isRunningAgent ──────────────────────
//
// Both channels back the same GetTerminalAgentStatus RPC (see that
// message's proto doc comment) — terminal.isRunningAgent just projects the
// one boolean field terminal.agentStatus's richer view also carries.

type terminalAgentStatusView struct {
	AgentRunning  bool   `json:"agentRunning"`
	AgentKind     string `json:"agentKind"`
	ReadyForInput bool   `json:"readyForInput"`
}

func registerTerminalAgentStatusChannels(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	getStatus := func(ctx context.Context, id Identity, ptyID string) (*infrafleetv1.GetTerminalAgentStatusResponse, error) {
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		return client.GetTerminalAgentStatus(ctx, &infrafleetv1.GetTerminalAgentStatusRequest{PtyId: ptyID})
	}

	r.Register("terminal.agentStatus", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalPtyIDArg](args, 0)
		if err != nil {
			return nil, err
		}
		resp, err := getStatus(ctx, id, in.PtyID)
		if err != nil {
			return nil, err
		}
		return terminalAgentStatusView{AgentRunning: resp.GetAgentRunning(), AgentKind: resp.GetAgentKind(), ReadyForInput: resp.GetReadyForInput()}, nil
	})

	r.Register("terminal.isRunningAgent", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalPtyIDArg](args, 0)
		if err != nil {
			return nil, err
		}
		resp, err := getStatus(ctx, id, in.PtyID)
		if err != nil {
			return nil, err
		}
		// Projects the SAME RPC's response down to one bool — see this
		// file's package doc comment for why isRunningAgent isn't a
		// separate RPC.
		return resp.GetAgentRunning(), nil
	})
}

// ── terminal.inspectProcess ─────────────────────────────────────────────

type terminalInspectProcessView struct {
	Known   bool   `json:"known"`
	Pid     int32  `json:"pid"`
	Command string `json:"command"`
	Cwd     string `json:"cwd"`
}

func registerTerminalInspectProcessChannel(r *Registry, client infrafleetv1.InfraFleetServiceClient) {
	r.Register("terminal.inspectProcess", func(ctx context.Context, id Identity, args []json.RawMessage) (any, error) {
		in, err := decodeArg[terminalPtyIDArg](args, 0)
		if err != nil {
			return nil, err
		}
		ctx = gatewaygrpc.AttachIdentity(ctx, usecase.Identity{TenantID: id.TenantID, UserID: id.UserID})
		resp, err := client.InspectTerminalProcess(ctx, &infrafleetv1.InspectTerminalProcessRequest{PtyId: in.PtyID})
		if err != nil {
			return nil, err
		}
		return terminalInspectProcessView{Known: resp.GetKnown(), Pid: resp.GetPid(), Command: resp.GetCommand(), Cwd: resp.GetCwd()}, nil
	})
}
