CREATE TABLE approvals (
    id CHAR(36) PRIMARY KEY,
    tenant_id CHAR(36) NOT NULL,
    request_id CHAR(36) NOT NULL,
    subject_type VARCHAR(20) NOT NULL,
    subject_id VARCHAR(64) NOT NULL,
    stage VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_by VARCHAR(64) NOT NULL,
    decided_by VARCHAR(64) NULL,
    decided_at TIMESTAMP(6) NULL,
    comment TEXT NOT NULL,
    due_at TIMESTAMP(6) NULL,
    version BIGINT NOT NULL DEFAULT 1,
    subject_digest CHAR(64) NOT NULL,
    self_approval_allowed TINYINT(1) NOT NULL DEFAULT 1,
    idempotency_key VARCHAR(128) NULL,
    reminded_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    pending_key VARCHAR(120) GENERATED ALWAYS AS (IF(status='pending', CONCAT(subject_type,':',subject_id), NULL)) STORED,
    UNIQUE KEY approvals_one_pending (tenant_id, pending_key),
    UNIQUE KEY approvals_idem (tenant_id, idempotency_key),
    INDEX approvals_by_request (tenant_id, request_id, created_at),
    INDEX approvals_due (tenant_id, status, due_at),
    INDEX approvals_inbox (tenant_id, status, created_at),
    CONSTRAINT fk_approvals_request FOREIGN KEY (request_id) REFERENCES requests(id),
    CONSTRAINT chk_approvals_subject_type CHECK (subject_type IN ('request_type','solution','findings','answer','plan','phase','task_list','pre_deploy')),
    CONSTRAINT chk_approvals_status CHECK (status IN ('pending','approved','rejected','cancelled','expired'))
) ENGINE=InnoDB;
