// src/main/dev-server/agent-ws-server.ts
// WebSocket server for accepting incoming agent connections (direct-websocket mode).
//
// Architecture:
//   Browser  → ws://:6768/        (existing OrcaRuntimeRpcServer — unchanged)
//   Agent    → ws://:6769/agent   (NEW — this file handles /agent path on HTTP server)
//
// The HTTP server's 'upgrade' event is shared. AgentWebSocketServer intercepts
// only upgrades to path '/agent'. All other paths pass through to existing handlers.
//
// Does NOT import from 'electron' — works in Node.js server mode.

import { WebSocketServer, WebSocket } from 'ws'
import type { IncomingMessage } from 'node:http'
import type { Server as HttpServer } from 'node:http'
import { SshChannelMultiplexer } from '../ssh/ssh-channel-multiplexer'
import { createWebSocketTransport } from './ws-transport'
import { runOrcaReceiverHandshake } from './ws-handshake'
import type { WsHandshakeInfo } from './ws-handshake'
import { AGENT_WS_PATH, AGENT_CONNECT_TIMEOUT_MS } from '../../shared/agent-wire-protocol'
import { Tracers } from '../../shared/trace/tracers'

// ─── Types ────────────────────────────────────────────────────────────────────

export type AgentConnectedInfo = WsHandshakeInfo

export type AgentConnectionCallback = (
  mux: SshChannelMultiplexer,
  info: AgentConnectedInfo
) => void

type PendingSlot = {
  callback: AgentConnectionCallback
  expireTimer: ReturnType<typeof setTimeout>
  onExpired: (reason: string) => void
}

// ─── AgentWebSocketServer ─────────────────────────────────────────────────────

export class AgentWebSocketServer {
  private wss: WebSocketServer | null = null
  /** Map<agentToken, PendingSlot> — slots waiting for agent to connect */
  private pendingSlots = new Map<string, PendingSlot>()
  private orcaVersion: string

  constructor(orcaVersion: string) {
    this.orcaVersion = orcaVersion
  }

  /**
   * Attach to an existing HTTP server, intercepting WS upgrades on AGENT_WS_PATH ('/agent').
   * Only intercepts path '/agent' — other paths pass through to existing handlers.
   *
   * Call once during server startup (server-bootstrap.ts → server/index.ts).
   */
  attach(httpServer: HttpServer): void {
    this.wss = new WebSocketServer({ noServer: true })

    httpServer.on('upgrade', (req: IncomingMessage, socket, head) => {
      const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`)
      if (url.pathname !== AGENT_WS_PATH) return  // not for us — pass through

      this.wss!.handleUpgrade(req, socket, head, (ws: WebSocket) => {
        this.handleConnection(ws)
      })
    })
  }

  /**
   * Register a slot for a specific agent token.
   * When an agent connects with this token and passes handshake → callback fires.
   *
   * Slot auto-expires after AGENT_CONNECT_TIMEOUT_MS (60s).
   *
   * @param agentToken   Unique token generated by DevServerRelayBridge
   * @param onConnected  Called with mux + info when agent connects successfully
   * @param onExpired    Called with descriptive error if agent doesn't connect in time
   * @returns disposer   Call to cancel slot (e.g. when DevServer is removed)
   */
  registerSlot(
    agentToken: string,
    onConnected: AgentConnectionCallback,
    onExpired: (reason: string) => void
  ): () => void {
    // Clear any existing slot for same token (idempotent re-register for reconnect)
    this.removeSlot(agentToken)

    const expireTimer = setTimeout(() => {
      this.pendingSlots.delete(agentToken)
      onExpired(
        `direct-websocket: Agent did not connect within ${AGENT_CONNECT_TIMEOUT_MS / 1000}s. ` +
        `Configure your agent with:\n` +
        `  ORCA_URL=ws://<orca-host>:6768${AGENT_WS_PATH}\n` +
        `  AGENT_TOKEN=${agentToken}`
      )
    }, AGENT_CONNECT_TIMEOUT_MS)

    this.pendingSlots.set(agentToken, { callback: onConnected, expireTimer, onExpired })

    return () => this.removeSlot(agentToken)
  }

  private removeSlot(agentToken: string): void {
    const slot = this.pendingSlots.get(agentToken)
    if (slot) {
      clearTimeout(slot.expireTimer)
      this.pendingSlots.delete(agentToken)
    }
  }

  private handleConnection(ws: WebSocket): void {
    // Why: runOrcaReceiverHandshake validates agentToken from handshake params.
    // We pass a validator that checks our slot map — unknown tokens are rejected early.
    runOrcaReceiverHandshake(
      ws,
      (token) => this.pendingSlots.has(token),
      this.orcaVersion
    )
      .then((info) => {
        const agentToken = info.agentToken ?? ''
        const slot = this.pendingSlots.get(agentToken)

        if (!slot) {
          // Race condition: slot expired between validate check and resolve
          ws.close(1008, 'Slot expired — agent token is no longer registered')
          return
        }

        // Consume slot (one-time use per connect cycle)
        this.removeSlot(agentToken)

        const span = Tracers.agentWsFlow.start({
          devServerId: info.devServerId ?? 'unknown',
          platform: info.platform ?? 'unknown',
          node: info.nodeVersion ?? 'unknown'
        })

        // Wire multiplexer and hand off to DevServerRelayBridge via callback
        // Why: agents connect via WebSocket (not SSH), so use a non-SSH error
        // message so users aren't confused by 'SSH connection lost' when the
        // underlying transport is a plain WebSocket.
        const transport = createWebSocketTransport(ws)
        const mux = new SshChannelMultiplexer(transport, {
          connectionLostMessage: 'Connection lost, reconnecting...'
        })

        // Track disconnect for tracing
        ws.once('close', (code, reason) => {
          const reasonStr = reason?.toString() || '(none)'
          span.step('disconnect', { code, reason: reasonStr })
        })

        span.step('connected', { token: agentToken.slice(0, 12) + '...' })
        slot.callback(mux, info)
      })
      .catch((err: Error) => {
        // ws is already closed by runOrcaReceiverHandshake on failure
        Tracers.agentWsFlow.start().fail(err, { phase: 'handshake' })
        console.warn('[AgentWsServer] Handshake rejected:', err.message)
      })
  }

  /** Stop the server and cancel all pending slots */
  stop(): void {
    for (const [token] of this.pendingSlots) {
      this.removeSlot(token)
    }
    this.wss?.close()
    this.wss = null
  }
}
