// src/relay/agent-connection-direct.ts
// Direct-websocket connection mode: Agent connects outbound to Orca Server.
//
// Token lifecycle:
//   - agentToken is a one-time use token generated by connect-agent.sh
//   - On any disconnect (auth failure, network drop, clean close), exit instead of retry
//   - systemd Restart=always + start.sh will obtain a fresh token on each restart
//
// Exit codes:
//   0 = clean close (code 1000)
//   1 = startup failure (missing token)
//   2 = session ended (abnormal close) — triggers systemd restart

import WebSocket from 'ws'
import type { AgentConfig } from './agent-config'
import type { ToolDefinition } from './agent-tool-registry'
import { createSession } from './agent-session'
import type { AgentLogger } from './agent-logger'
import { createTracer } from '../shared/trace'

const connTracer = createTracer('agent:connection')

export async function connectDirect(
  config: AgentConfig,
  tools: ToolDefinition[],
  log: AgentLogger
): Promise<never> {
  if (!config.agentToken) {
    log.error('AGENT_TOKEN is required for direct-websocket mode but is not set.')
    log.error('Obtain a token with: bash deploy/dev/scripts/connect-agent.sh')
    process.exit(1)
  }

  let lastHandshakeOk = false

  const connSpan = connTracer.start({ url: config.orcaUrl })
  log.info(`Connecting to ${config.orcaUrl} ...`)

  const ws = new WebSocket(config.orcaUrl, {
    headers: { 'User-Agent': 'orca-dev-agent/2.1.0' },
    rejectUnauthorized: config.tlsRejectUnauthorized,
  })

  const session = createSession(config, tools, log)
  session.onHandshakeOk(() => {
    lastHandshakeOk = true
    connSpan.step('handshake-ok')
    log.info('Connection established and authenticated.')
  })
  session.start(ws)

  ws.once('close', (code: number) => {
    session.stop()

    if (code === 1000) {
      connSpan.ok({ code })
      log.info('Connection closed cleanly (code=1000). Shutting down.')
      setTimeout(() => process.exit(0), 100)
      return
    }

    if (lastHandshakeOk) {
      connSpan.fail(`connection dropped after handshake`, { code })
      log.warn(`Connection dropped after handshake (code=${code}) — exiting for systemd restart`)
    } else {
      connSpan.fail(`token rejected or expired`, { code })
      log.error(`Connection closed before handshake (code=${code}) — token rejected or expired`)
    }

    // NEVER retry internally: token is one-time use.
    // systemd Restart=always ensures start.sh fetches a fresh token.
    setTimeout(() => process.exit(2), 200)
  })

  // This promise never resolves — the process runs until process.exit() is called
  return new Promise<never>(() => {})
}
