// src/main/dev-server/agent-ws-server.ts
// WebSocket server for accepting incoming agent connections (direct-websocket mode).
//
// Architecture:
//   Browser  → ws://:6768/        (existing OrcaRuntimeRpcServer — unchanged)
//   Agent    → ws://:6769/agent   (NEW — this file handles /agent path on HTTP server)
//
// The HTTP server's 'upgrade' event is shared. AgentWebSocketServer intercepts
// only upgrades to path '/agent'. All other paths pass through to existing handlers.
//
// Does NOT import from 'electron' — works in Node.js server mode.

import { WebSocketServer } from 'ws'
import type { WebSocket } from 'ws'
import type { IncomingMessage } from 'node:http'
import type { Server as HttpServer } from 'node:http'
import { createHash } from 'node:crypto' // FIX TASK-AWS-002: for SHA-256 token hashing
import { SshChannelMultiplexer } from '../ssh/ssh-channel-multiplexer'
import { createWebSocketTransport } from './ws-transport'
import { runOrcaReceiverHandshake } from './ws-handshake'
import type { WsHandshakeInfo } from './ws-handshake'
import { AGENT_WS_PATH, AGENT_CONNECT_TIMEOUT_MS } from '../../shared/agent-wire-protocol'
import { Tracers } from '../../shared/trace/tracers'

// Mirrors src/server/index.ts's rpcPort/httpPort derivation — this file has no
// access to that module's local consts, and the two must never drift apart
// since agents are told to connect to whichever port this computes.
function agentWsPort(): number {
  const rpcPort = Number.parseInt(process.env.ORCA_PORT ?? '6768', 10)
  return Number.parseInt(process.env.ORCA_HTTP_PORT ?? String(rpcPort + 1), 10)
}

// ─── Types ────────────────────────────────────────────────────────────────────

export type AgentConnectedInfo = WsHandshakeInfo

export type AgentConnectionCallback = (mux: SshChannelMultiplexer, info: AgentConnectedInfo) => void

type PendingSlot = {
  callback: AgentConnectionCallback
  expireTimer: ReturnType<typeof setTimeout>
  onExpired: (reason: string) => void
}

// ─── AgentWebSocketServer ─────────────────────────────────────────────────────

export class AgentWebSocketServer {
  private wss: WebSocketServer | null = null
  /**
   * FIX TASK-AWS-002: Store SHA-256(agentToken) as map key, not plaintext.
   * Prevents token extraction from heap dumps or core files.
   * Map<SHA-256(agentToken), PendingSlot>
   */
  private pendingSlots = new Map<string, PendingSlot>()
  private orcaVersion: string

  constructor(orcaVersion: string) {
    this.orcaVersion = orcaVersion
  }

  /**
   * Attach to an existing HTTP server, intercepting WS upgrades on AGENT_WS_PATH ('/agent').
   * Only intercepts path '/agent' — other paths pass through to existing handlers.
   *
   * Call once during server startup (server-bootstrap.ts → server/index.ts).
   */
  attach(httpServer: HttpServer): void {
    this.wss = new WebSocketServer({ noServer: true })

    httpServer.on('upgrade', (req: IncomingMessage, socket, head) => {
      const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`)
      if (url.pathname !== AGENT_WS_PATH) {
        return
      } // not for us — pass through

      this.wss!.handleUpgrade(req, socket, head, (ws: WebSocket) => {
        this.handleConnection(ws)
      })
    })
  }

  /**
   * Register a slot for a specific agent token.
   * When an agent connects with this token and passes handshake → callback fires.
   *
   * Slot auto-expires after AGENT_CONNECT_TIMEOUT_MS (60s).
   *
   * @param agentToken   Unique token generated by DevServerRelayBridge
   * @param onConnected  Called with mux + info when agent connects successfully
   * @param onExpired    Called with descriptive error if agent doesn't connect in time
   * @returns disposer   Call to cancel slot (e.g. when DevServer is removed)
   */
  registerSlot(
    agentToken: string,
    onConnected: AgentConnectionCallback,
    onExpired: (reason: string) => void
  ): () => void {
    // FIX TASK-AWS-002: Store SHA-256 hash of token as map key.
    // The plaintext token is only used to build the setup instructions below.
    // The hash is used for all internal lookups — token never stored in pendingSlots.
    const tokenHash = hashToken(agentToken)

    // Clear any existing slot for same token (idempotent re-register for reconnect)
    this.removeSlotByHash(tokenHash)

    const expireTimer = setTimeout(() => {
      this.pendingSlots.delete(tokenHash)
      onExpired(
        `direct-websocket: Agent did not connect within ${AGENT_CONNECT_TIMEOUT_MS / 1000}s. ` +
          `Configure your agent with:\n` +
          // Agent WS listens on httpPort (rpcPort+1, default 6769 — see header comment),
          // not rpcPort (6768, the browser/RPC WS) — matches src/server/index.ts's split.
          `  ORCA_URL=ws://<orca-host>:${agentWsPort()}${AGENT_WS_PATH}\n` +
          `  AGENT_TOKEN=${agentToken}`
      )
    }, AGENT_CONNECT_TIMEOUT_MS)

    this.pendingSlots.set(tokenHash, { callback: onConnected, expireTimer, onExpired })

    return () => this.removeSlotByHash(tokenHash)
  }

  private removeSlotByHash(tokenHash: string): void {
    const slot = this.pendingSlots.get(tokenHash)
    if (slot) {
      clearTimeout(slot.expireTimer)
      this.pendingSlots.delete(tokenHash)
    }
  }

  private handleConnection(ws: WebSocket): void {
    // Keep connection alive through reverse proxies (ALB/Cloudflare)
    const wsAnyPing = ws as unknown as { isAlive: boolean; ping: () => void; terminate: () => void }
    const keepAliveInterval = setInterval(() => {
      wsAnyPing.ping()
    }, 30_000)

    ws.on('close', () => clearInterval(keepAliveInterval))

    // [FIX CR-TRACE-013] span mở NGAY khi socket upgrade thành công, TRƯỚC
    // khi biết kết quả handshake — thay vì tạo span mồ côi ngẫu nhiên trong
    // .catch() như trước (id không liên kết được với attempt connect nào).
    const span = Tracers.agentWsTokenVerifyFlow.start()

    // FIX TASK-AWS-002: Validate against SHA-256 hash of incoming token.
    // The validator receives the plaintext token from the handshake, hashes it,
    // and checks the hashed map — so plaintext is only held in the transient
    // handshake stack frame, never in the long-lived pendingSlots map.
    runOrcaReceiverHandshake(
      ws,
      (token) => {
        // KHÔNG log token đầy đủ — chỉ 12 ký tự đầu, theo tiền lệ dòng log hiện có.
        span.step('tokenLookup', { tokenPrefix: `${token.slice(0, 12)}...` })
        return this.pendingSlots.has(hashToken(token))
      },
      this.orcaVersion
    )
      .then((info) => {
        const agentToken = info.agentToken ?? ''
        const tokenHash = hashToken(agentToken)
        const slot = this.pendingSlots.get(tokenHash)

        if (!slot) {
          // Race condition: slot expired between validate check and resolve
          span.fail('slot-expired', { devServerId: info.devServerId ?? 'unknown' })
          ws.close(1008, 'Slot expired — agent token is no longer registered')
          return
        }

        // FIX TASK-AWS-002: Consume slot by hash
        this.removeSlotByHash(tokenHash)
        span.ok({ devServerId: info.devServerId ?? 'unknown', sessionId: info.sessionId })

        // agentWs:lifecycle (KHÔNG ĐỔI — vẫn là span riêng cho connect→disconnect)
        const lifecycleSpan = Tracers.agentWsFlow.start({
          devServerId: info.devServerId ?? 'unknown',
          platform: info.platform ?? 'unknown',
          node: info.nodeVersion ?? 'unknown'
        })

        // TEMP DIAG BUG-FE-PTY-001: tcpdump + agent-side instrumentation both
        // point at the BACKEND initiating the close (agent's ws library
        // auto-echoes a received CLOSE frame via Receiver.receiverOnConclude)
        // — but no explicit ws.close() call site was found anywhere in this
        // file, dev-server-relay-bridge.ts, or ssh-channel-multiplexer.ts
        // that fires outside a reactive/handshake-time path. Wrap this
        // session's own ws.close()/terminate() to catch it at the source.
        const diagDevServerId = info.devServerId ?? 'unknown'
        const diagOrigClose = ws.close.bind(ws)
        const diagOrigTerminate = ws.terminate.bind(ws)
        ;(ws as unknown as { close: typeof ws.close }).close = ((...args: Parameters<typeof diagOrigClose>) => {
          console.error(
            `[DIAG BUG-FE-PTY-001] backend ws.close() called devServerId=${diagDevServerId} args=${JSON.stringify(args)} readyState=${ws.readyState}\n${new Error('close call site').stack}`
          )
          return diagOrigClose(...args)
        }) as typeof ws.close
        ;(ws as unknown as { terminate: typeof ws.terminate }).terminate = (() => {
          console.error(
            `[DIAG BUG-FE-PTY-001] backend ws.terminate() called devServerId=${diagDevServerId} readyState=${ws.readyState}\n${new Error('terminate call site').stack}`
          )
          return diagOrigTerminate()
        }) as typeof ws.terminate

        // Wire multiplexer and hand off to DevServerRelayBridge via callback
        // Why: agents connect via WebSocket (not SSH), so use a non-SSH error
        // message so users aren't confused by 'SSH connection lost' when the
        // underlying transport is a plain WebSocket.
        const transport = createWebSocketTransport(ws)
        const mux = new SshChannelMultiplexer(transport, {
          connectionLostMessage: 'Connection lost, reconnecting...'
        })

        // Track disconnect for tracing
        ws.once('close', (code, reason) => {
          const reasonStr = reason?.toString() || '(none)'
          lifecycleSpan.step('disconnect', { code, reason: reasonStr })
        })

        lifecycleSpan.step('connected', { token: `${agentToken.slice(0, 12)}...` })
        slot.callback(mux, info)
      })
      .catch((err: Error) => {
        // [FIX CR-TRACE-013] dùng lại `span` đã mở từ đầu handleConnection()
        // thay vì tạo span mồ côi mới — nay liên kết được "socket X connect
        // lúc nào → fail ở bước nào". ws đã được đóng bởi runOrcaReceiverHandshake.
        span.fail(err, { reason: 'invalid-token' })
        console.warn('[AgentWsServer] Handshake rejected:', err.message)
      })
  }

  /** Stop the server and cancel all pending slots */
  stop(): void {
    // FIX TASK-AWS-002: keys are now hashes (not plaintext tokens)
    for (const [tokenHash] of this.pendingSlots) {
      this.removeSlotByHash(tokenHash)
    }
    this.wss?.close()
    this.wss = null
  }
}

// ── Helper: SHA-256 hash token ─────────────────────────────────────────────────
// FIX TASK-AWS-002: Store hashed tokens only in memory.
// SHA-256 is deterministic and fast (no salt needed here — it's a lookup key,
// not a password hash; the security goal is preventing token recovery from
// heap dumps, not collision resistance).
function hashToken(token: string): string {
  return createHash('sha256').update(token, 'utf8').digest('hex')
}
